### ISSUE TITLE
Error in solving a period using linux GCAM6.0

### ISSUE THREAD

**Issue by climate-change-ucsb** [JGCRI/gcam-core#451]
I am using GCAM6.0 on Linux, and got an error when solving the period 2015 in some of my scenarios. Any comment?

ERROR:Invalid share for biomass liquids in India log(share) =  inf
ERROR:Invalid share for biomass liquids in India log(share) =  inf
Error adding to demand in marketplace for: elect_td_ind, region: India, value: -nan
Error adding to demand in marketplace for: regional oil, region: India, value: -nan
Error adding to demand in marketplace for: wholesale gas, region: India, value: -nan
Error adding to supply in marketplace for: refining, region: India, value: -nan
Error adding to supply in marketplace for: oil-credits, region: India, value: -nan
Error adding to demand in marketplace for: CO2, region: India, value: -nan
......

**Comment by Silviameteoro** [comment]
Did your period solve? I think if it says that the period solved, you should be OK. Hopefully others can comment as well.

**Comment by climate-change-ucsb** [comment]
> Did your period solve? I think if it says that the period solved, you should be OK. Hopefully others can comment as well.

It is solved most of the time, but sometimes it is not.

**Comment by Silviameteoro** [comment]
I suggest that you provide more details on what you are changing ... 2015 is a calibrated year, thus it is weird that it does not solve unless you are changing something ...

**Comment by climate-change-ucsb** [comment]
> I suggest that you provide more details on what you are changing ... 2015 is a calibrated year, thus it is weird that it does not solve unless you are changing something ...

That's a helpful comment! I will add to this post if I cannot solve the period!
